### ISSUE TITLE
bug: Event list on location view includes inactive events

### ISSUE THREAD

**Issue by evanpetzoldt** [F3-Nation/f3-nation-map#54]
### Describe the bug

I noticed that if an event is inactive `events.is_active=0`, it correctly does not display on the map, but I can still see it when clicking into the location:

![Image](https://github.com/user-attachments/assets/2e4e35ab-b9d9-433b-aada-0cd0e531b192)

### To reproduce

You can see this for `events.id=1`, https://staging.map.f3nation.com/?eventId=3&locationId=1

**Comment by dnishiyama** [comment]
This should be resolved in 2.0.4. Can you confirm? @taterhead247 @evanpetzoldt

**Comment by evanpetzoldt** [comment]
I just checked staging, and it still shows up. Additionally, the active event on Tuesday does not show up as a map pin (only Thursday is shown). Event ids 1-3 for reference

![Screenshot_20250503-160737.png](https://github.com/user-attachments/assets/a6d2846b-b8ad-4b9c-b05c-6dcddc5970e6)

![Screenshot_20250503-160717.png](https://github.com/user-attachments/assets/4e3e3f51-8aa2-4b6e-90d0-d8fe11decd47)

**Comment by dnishiyama** [comment]
oh dang. I did a "hotfix" directly into production. So it wasn't in staging. Sorry about that. I've merged it in now. I'll double check it tomorrow

**Comment by taterhead247** [comment]
Fixed in 2.1.0 prod
