### ISSUE TITLE
bug: No place to remove old notes

### ISSUE THREAD

**Issue by forrestchev** [F3-Nation/f3-nation-map#60]
### Provide environment information

We moved a location to a new place and cannot edit the "notes" field.

![Image](https://github.com/user-attachments/assets/4e63f113-0b5a-46cc-98af-f51c5c769b27)

### Describe the bug

I moved an AO but it still has the old description of the location in a "hidden" notes field.

**Comment by forrestchev** [comment]
Hello,

I do not see a spot to edit this in the admin panel. If I'm missing
something, please let me know.

Forrest

**Comment by taterhead247** [comment]
@forrestchev can you go to https://map.f3nation.com/admin/workouts and search for The Goat? I was able to edit the description field and it updated the map.

**Comment by taterhead247** [comment]
@dnishiyama this is event 49660. When investigating, I noticed that when I edit the Event in Admin Portal, the Location field is blank. I traced it back, the Location is owned by the Rowlett Region.

@forrestchev at the time we migrated to the new map, was The Goat part of the Rowlett region?

**Comment by forrestchev** [comment]
That is correct

**Comment by dnishiyama** [comment]
I believe this is resolved. Please reopen if I'm mistaken

**Comment by forrestchev** [comment]
Hey Fellas,
The issue still remains. Here's what I'm seeing... (two pictures below)

*In the Admin Portal (the correct information)*
[image: image.png]

*On the F3 Nation Map (incorrect information)*
[image: image.png]

**Comment by forrestchev** [comment]
@taterhead247 it looks like there are two workouts and one needs to be deleted. I get an error when trying to delete - can you please delete this point for me? This will probably fix the website.

![Image](https://github.com/user-attachments/assets/5f970bfb-d683-48b0-a030-bf4631d481eb)

**Comment by taterhead247** [comment]
@forrestchev I deleted the requested event. But... The Rowlett one is gone now too. Please tell me you deleted it? And not that me deleting one deleted the other.

**Comment by forrestchev** [comment]
That’s interesting. I tried to delete the bad one last night but kept
getting an error.
Hey it’s no worries man! I can just go add it again

**Comment by dnishiyama** [comment]
Thanks for letting us know about all this. I'm working on improving this process

**Comment by forrestchev** [comment]
No worries it's all fixed now!
